#!/bin/bash

# set_hidpi.sh - Script to set HiDPI scaling for 4K displays
# Usage: ./set_hidpi.sh [OPTIONS] [DPI_VALUE]

LOG_FILE="$HOME/.config/awesome/logs/hidpi.log"
XPROFILE="$HOME/.xprofile"

log() {
    mkdir -p "$(dirname "$LOG_FILE")"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
    echo "$1"
}

# Set DPI and export environment variables
set_dpi() {
    local dpi="${1:-192}"
    local scale=$((dpi / 96))
    
    log "Setting DPI to $dpi (${scale}x scaling)"
    
    # Set X resource DPI
    echo "Xft.dpi: $dpi" | xrdb -merge
    
    # Environment variables for current session
    export GDK_SCALE=$scale
    export GDK_DPI_SCALE=$(echo "scale=2; 1/$scale" | bc)
    export QT_AUTO_SCREEN_SCALE_FACTOR=1
    export QT_SCALE_FACTOR=$scale
    
    # Restart Awesome to apply changes
    if command -v awesome-client &>/dev/null; then
        echo "awesome.restart()" | awesome-client 2>>"$LOG_FILE"
        log "Awesome restarted"
    fi
    
    log "HiDPI set to $dpi. Re-login for full effect."
}

# Create/update xprofile for persistent HiDPI settings
create_xprofile() {
    local dpi="${1:-192}"
    local scale=$((dpi / 96))
    # Calculate dpi_scale as inverse without bc
    local dpi_scale="0.5"
    [ "$scale" -eq 1 ] && dpi_scale="1"
    [ "$scale" -eq 3 ] && dpi_scale="0.33"
    
    # Backup existing xprofile
    [ -f "$XPROFILE" ] && cp "$XPROFILE" "${XPROFILE}.bak.$(date +%Y%m%d%H%M%S)"
    
    cat > "$XPROFILE" << EOF
# HiDPI settings - Generated by set_hidpi.sh
echo "Xft.dpi: $dpi" | xrdb -merge

# GTK applications
export GDK_SCALE=$scale
export GDK_DPI_SCALE=$dpi_scale

# Qt applications
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_SCALE_FACTOR=$scale

# Java applications
export _JAVA_OPTIONS='-Dsun.java2d.uiScale=$scale'

# Electron applications
export ELECTRON_FORCE_DEVICE_SCALE_FACTOR=$scale

# Load user Xresources
[ -f "\$HOME/.Xresources" ] && xrdb -merge "\$HOME/.Xresources"
EOF
    
    chmod +x "$XPROFILE"
    log "Created $XPROFILE with DPI $dpi"
}

show_help() {
    echo "Usage: $0 [OPTION] [DPI]"
    echo ""
    echo "Options:"
    echo "  --set [DPI]       Set DPI for current session (default: 192)"
    echo "  --persist [DPI]   Create xprofile for persistent HiDPI"
    echo "  --help            Show this help"
    echo ""
    echo "DPI values: 96 (1x), 144 (1.5x), 192 (2x), 288 (3x)"
}

case "$1" in
    --set)      set_dpi "$2" ;;
    --persist)  create_xprofile "$2" ;;
    --help|-h)  show_help ;;
    [0-9]*)     set_dpi "$1" ;;  # Backward compatible: just DPI value
    *)          show_help ;;
esac

exit 0